### ISSUE TITLE
大佬有不用cuda排序的版本吗  因为电脑不支持torch1.5  非常感谢

### ISSUE THREAD

**Issue by zzybj** [lilanxiao/Rotated_IoU#3]

**Comment by zzybj** [comment]
> 你好，我只写了CUDA的版本。按照你的问题，我有三个建议，优先级依次递减：
> 
> 1. 尝试用低版本torch进行编译。我给torch的版本限定了1.5是因为我只在这个版本下测试过，低版本的torch可能也能编译。
> 2. 尝试安装torch 1.5。无法安装torch 1.5常见的原因有Nvidia驱动版本不符，python环境冲突等等，经过排查一般是可以安装的。
> 3. 如果实在搞不定可以自己用C++进行重构。因为CUDA版本和C++的核心逻辑是一致的， 只是CUDA版本可以自动并行化而已，在C下可以使用循环代替CUDA的并行运算。添加Pytorch C++拓展的具体操作可以参考[这个教程](https://pytorch.org/tutorials/advanced/cpp_extension.html)。但是这是最不推荐的，因为不能使用GPU加速，数据在CPU和GPU之间来回传递也会产生Overhead。如果需要计算的Bounding Box多的话会非常慢。
> 
> 祝好

大佬 您好  我在其他设备上用torch1.5尝试了一下，但是还是报错，您能看看哪出错了吗  十分感谢
running install
running bdist_egg
running egg_info
creating sort_vertices.egg-info
writing sort_vertices.egg-info/PKG-INFO
writing dependency_links to sort_vertices.egg-info/dependency_links.txt
writing top-level names to sort_vertices.egg-info/top_level.txt
writing manifest file 'sort_vertices.egg-info/SOURCES.txt'
reading manifest file 'sort_vertices.egg-info/SOURCES.txt'
writing manifest file 'sort_vertices.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'sort_vertices' extension
creating /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build
creating /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6
Emitting ninja build file /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda-8.0/bin/nvcc -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/TH -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-8.0/include -I/home/user1/anaconda3/envs/yl/include/python3.6m -c -c /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/sort_vert_kernel.cu -o /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sort_vertices -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_35,code=sm_35 -std=c++14
FAILED: /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert_kernel.o 
/usr/local/cuda-8.0/bin/nvcc -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/TH -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-8.0/include -I/home/user1/anaconda3/envs/yl/include/python3.6m -c -c /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/sort_vert_kernel.cu -o /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sort_vertices -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_35,code=sm_35 -std=c++14
/bin/sh: /usr/local/cuda-8.0/bin/nvcc: No such file or directory
[2/2] c++ -MMD -MF /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert.o.d -pthread -B /home/user1/anaconda3/envs/yl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/TH -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-8.0/include -I/home/user1/anaconda3/envs/yl/include/python3.6m -c -c /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/sort_vert.cpp -o /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sort_vertices -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert.o 
c++ -MMD -MF /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert.o.d -pthread -B /home/user1/anaconda3/envs/yl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/TH -I/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-8.0/include -I/home/user1/anaconda3/envs/yl/include/python3.6m -c -c /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/sort_vert.cpp -o /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/build/temp.linux-x86_64-3.6/sort_vert.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sort_vertices -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/utils.h:2:0,
                 from /media/data/zhengzy/YOLO/Rotated_IoU-master/cuda_op/sort_vert.cpp:1:
/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/user1/anaconda3/envs/yl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by zzybj** [comment]
> 你好，我只写了CUDA的版本。按照你的问题，我有三个建议，优先级依次递减：
> 
> 1. 尝试用低版本torch进行编译。我给torch的版本限定了1.5是因为我只在这个版本下测试过，低版本的torch可能也能编译。
> 2. 尝试安装torch 1.5。无法安装torch 1.5常见的原因有Nvidia驱动版本不符，python环境冲突等等，经过排查一般是可以安装的。
> 3. 如果实在搞不定可以自己用C++进行重构。因为CUDA版本和C++的核心逻辑是一致的， 只是CUDA版本可以自动并行化而已，在C下可以使用循环代替CUDA的并行运算。添加Pytorch C++拓展的具体操作可以参考[这个教程](https://pytorch.org/tutorials/advanced/cpp_extension.html)。但是这是最不推荐的，因为不能使用GPU加速，数据在CPU和GPU之间来回传递也会产生Overhead。如果需要计算的Bounding Box多的话会非常慢。
> 
> 祝好

大佬 您好 能帮忙看看这个错误吗 这是用torch1.5 ，install之后报的错误
running install
running bdist_egg
running egg_info
writing sort_vertices.egg-info/PKG-INFO
writing dependency_links to sort_vertices.egg-info/dependency_links.txt
writing top-level names to sort_vertices.egg-info/top_level.txt
reading manifest file 'sort_vertices.egg-info/SOURCES.txt'
writing manifest file 'sort_vertices.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'sort_vertices' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user1/anaconda3/lib/python3.6/site-packages/torch/include -I/home/user1/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/user1/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/user1/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/user1/anaconda3/include/python3.6m -c sort_vert.cpp -o build/temp.linux-x86_64-3.6/sort_vert.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sort_vertices -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from sort_vert.cpp:1:0:
utils.h:27:64: warning: backslash-newline at end of file
 #define CHECK_IS_BOOL(x)                                       \
                                                                ^
sort_vert.cpp: In function ‘at::Tensor sort_vertices(at::Tensor, at::Tensor, at::Tensor)’:
utils.h:12:73: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_contiguous(), #x " must ne a contiguous tensor");       \
                                                                         ^
sort_vert.cpp:7:5: note: in expansion of macro ‘CHECK_CONTIGUOUS’
     CHECK_CONTIGUOUS(vertices);
     ^
utils.h:12:73: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_contiguous(), #x " must ne a contiguous tensor");       \
                                                                         ^
sort_vert.cpp:8:5: note: in expansion of macro ‘CHECK_CONTIGUOUS’
     CHECK_CONTIGUOUS(mask);
     ^
utils.h:12:73: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_contiguous(), #x " must ne a contiguous tensor");       \
                                                                         ^
sort_vert.cpp:9:5: note: in expansion of macro ‘CHECK_CONTIGUOUS’
     CHECK_CONTIGUOUS(num_valid);
     ^
utils.h:7:61: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor");   \
                                                             ^
sort_vert.cpp:10:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(vertices);
     ^
utils.h:7:61: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor");   \
                                                             ^
sort_vert.cpp:11:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(mask);
     ^
utils.h:7:61: error: ‘TORCH_CHECK’ was not declared in this scope
         TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor");   \
                                                             ^
sort_vert.cpp:12:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(num_valid);
     ^
utils.h:24:49: error: ‘TORCH_CHECK’ was not declared in this scope
                     #x " must be a float tensor");              \
                                                 ^
sort_vert.cpp:13:5: note: in expansion of macro ‘CHECK_IS_FLOAT’
     CHECK_IS_FLOAT(vertices);
     ^
utils.h:30:48: error: ‘TORCH_CHECK’ was not declared in this scope
                     #x " must be a bool tensor");             \
                                                ^
sort_vert.cpp:14:5: note: in expansion of macro ‘CHECK_IS_BOOL’
     CHECK_IS_BOOL(mask);
     ^
utils.h:18:47: error: ‘TORCH_CHECK’ was not declared in this scope
                     #x " must be a int tensor");            \
                                               ^
sort_vert.cpp:15:5: note: in expansion of macro ‘CHECK_IS_INT’
     CHECK_IS_INT(num_valid);
     ^
sort_vert.cpp:23:54: error: expected primary-expression before ‘float’
     sort_vertices_wrapper(b, n, m, vertices.data_ptr<float>(), mask.data_ptr<bool>(),
                                                      ^
sort_vert.cpp:23:78: error: expected primary-expression before ‘bool’
     sort_vertices_wrapper(b, n, m, vertices.data_ptr<float>(), mask.data_ptr<bool>(),
                                                                              ^
sort_vert.cpp:24:45: error: expected primary-expression before ‘int’
                          num_valid.data_ptr<int>(), idx.data_ptr<int>());
                                             ^
sort_vert.cpp:24:66: error: expected primary-expression before ‘int’
                          num_valid.data_ptr<int>(), idx.data_ptr<int>());
                                                                  ^
error: command 'gcc' failed with exit status 1

**Comment by lilanxiao** [comment]
关键的报错是这一句：

> /bin/sh: /usr/local/cuda-8.0/bin/nvcc: No such file or directory

nvcc是nvidia的CUDA编译器，类似于c语言的gcc。这里的报错表示找不到nvcc。最可能的原因是没有安装cuda-toolkit。

安装方法参考官网的教程。注意必须使用10.2版本。
> https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by cmpute** [comment]
https://github.com/cmpute/d3d/blob/master/d3d/box/__init__.py
我写的版本，目前支持torch1.4+，理论上再往下支持也可以，只不过要改CMake
